version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/usr/src/app
    depends_on:
      - db
    networks:
        - switching-network
    command: ["gunicorn", "-b", "0.0.0.0:5000", "src.app:create_app()"]

  jobs:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PYTHONPATH=/usr/src/app
    depends_on:
      - api
    networks:
      - switching-network
    command: ["python", "src/jobs.py"]

  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - switching-network
    ports:
      - "5432:5432"

networks:
  switching-network:
    driver: bridge

volumes:
  postgres-data: