FROM python:3.9-slim

WORKDIR /usr/src/app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONPATH=/usr/src/app

EXPOSE 5000

CMD ["gunicorn", "-b", "0.0.0.0:5000", "src.app:create_app()"]